# Generated by Django 3.1.12 on 2021-06-29 06:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_me', wagtail.core.fields.RichTextField(default='Write about yourself in here!')),
                ('resume_experience', wagtail.core.fields.StreamField([('resume_experience', wagtail.core.blocks.StructBlock([('job_discription', wagtail.core.blocks.CharBlock()), ('job_title', wagtail.core.blocks.CharBlock()), ('job_start_date', wagtail.core.blocks.CharBlock()), ('job_end_date', wagtail.core.blocks.CharBlock()), ('job_responsibilities', wagtail.core.blocks.RichTextBlock())]))], default='')),
                ('resume_education', wagtail.core.fields.StreamField([('resume_education', wagtail.core.blocks.StructBlock([('edu_discription', wagtail.core.blocks.CharBlock()), ('edu_title', wagtail.core.blocks.CharBlock()), ('edu_start_date', wagtail.core.blocks.CharBlock()), ('edu_end_date', wagtail.core.blocks.CharBlock()), ('edu_responsibilities', wagtail.core.blocks.RichTextBlock())]))], default='')),
                ('skill_discription', models.CharField(max_length=256, null=True)),
                ('skills', wagtail.core.fields.StreamField([('skill', wagtail.core.blocks.StructBlock([('skill_title', wagtail.core.blocks.CharBlock()), ('skill_level', wagtail.core.blocks.IntegerBlock())]))], default='')),
                ('recent_projects', wagtail.core.fields.StreamField([('recent_projects', wagtail.core.blocks.StructBlock([('project_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('project_date', wagtail.core.blocks.CharBlock()), ('project_title', wagtail.core.blocks.CharBlock()), ('project_github_url', wagtail.core.blocks.URLBlock())]))], default='')),
                ('my_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
