# Generated by Django 3.1.12 on 2021-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_me_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
