# Generated by Django 3.1.12 on 2021-06-30 11:23

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210630_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_me_footer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='call_me',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='email_me',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='open_hours',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='resume_education',
            field=wagtail.core.fields.StreamField([('resume_education', wagtail.core.blocks.StructBlock([('edu_title', wagtail.core.blocks.CharBlock()), ('edu_start_date', wagtail.core.blocks.CharBlock()), ('edu_end_date', wagtail.core.blocks.CharBlock()), ('edu_responsibilities', wagtail.core.blocks.RichTextBlock())]))], default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='resume_experience',
            field=wagtail.core.fields.StreamField([('resume_experience', wagtail.core.blocks.StructBlock([('job_title', wagtail.core.blocks.CharBlock()), ('job_start_date', wagtail.core.blocks.CharBlock()), ('job_end_date', wagtail.core.blocks.CharBlock()), ('job_responsibilities', wagtail.core.blocks.RichTextBlock())]))], default=''),
        ),
    ]
