# Generated by Django 3.1.12 on 2021-06-30 13:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210630_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='my_services',
            field=wagtail.core.fields.StreamField([('my_services', wagtail.core.blocks.StructBlock([('job_title', wagtail.core.blocks.CharBlock()), ('job_discription', wagtail.core.blocks.RichTextBlock())]))], default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_me_footer',
            field=wagtail.core.fields.RichTextField(default='Write about yourself in here!'),
        ),
    ]
