# Generated by Django 3.1.12 on 2021-06-30 13:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210630_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='areas_of_interest',
            field=wagtail.core.fields.StreamField([('areas_of_interest', wagtail.core.blocks.StructBlock([('areas_of_interest_title', wagtail.core.blocks.CharBlock()), ('areas_of_interest_discription', wagtail.core.blocks.RichTextBlock())]))], default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='my_services',
            field=wagtail.core.fields.StreamField([('my_services', wagtail.core.blocks.StructBlock([('my_services_title', wagtail.core.blocks.CharBlock())]))], default=''),
        ),
    ]
