# Generated by Django 3.1.12 on 2021-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210630_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='telegram',
            field=models.URLField(blank=True),
        ),
    ]
