# Generated by Django 3.1.12 on 2021-07-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='favicon',
        ),
    ]
